Fix AttributeError: remove accidental assignment in regex search
Fixed line 214: 'html.match =' should just be 're.search()'
This was causing AttributeError: 'str' object has no attribute 'match'